/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "app-background": "var(--app-background)",
        "berry-hill": "var(--berry-hill)",
        "blue-purp": "var(--blue-purp)",
        "bright-purple": "var(--bright-purple)",
        "chat-box-dark-mode": "var(--chat-box-dark-mode)",
        "chat-box-lavender": "var(--chat-box-lavender)",
        "chat-box-purp": "var(--chat-box-purp)",
        "dark-green": "var(--dark-green)",
        "darker-mystic-purple": "var(--darker-mystic-purple)",
        "deactivated-button": "var(--deactivated-button)",
        "deactivated-button-text": "var(--deactivated-button-text)",
        "dm-red": "var(--dm-red)",
        "extra-faded-gray": "var(--extra-faded-gray)",
        "extra-light-gray": "var(--extra-light-gray)",
        "faded-gray": "var(--faded-gray)",
        "faded-gray-on-white": "var(--faded-gray-on-white)",
        "faded-mauve": "var(--faded-mauve)",
        "faded-purp": "var(--faded-purp)",
        "green-text-on-gray-on-white": "var(--green-text-on-gray-on-white)",
        "insights-2": "var(--insights-2)",
        "insights-3": "var(--insights-3)",
        "insights-4": "var(--insights-4)",
        "insights-5": "var(--insights-5)",
        "jaded-magenta": "var(--jaded-magenta)",
        "lavendar-rose": "var(--lavendar-rose)",
        "lilac-bush": "var(--lilac-bush)",
        "lime-green": "var(--lime-green)",
        "lime-green-on-gray-on-white": "var(--lime-green-on-gray-on-white)",
        magenta: "var(--magenta)",
        "mid-green": "var(--mid-green)",
        "mystic-purple": "var(--mystic-purple)",
        "new-black": "var(--new-black)",
        "new-dark-gray": "var(--new-dark-gray)",
        "new-white": "var(--new-white)",
        orange: "var(--orange)",
        periwinkle: "var(--periwinkle)",
        plum: "var(--plum)",
        red: "var(--red)",
        "text-box": "var(--text-box)",
        "text-placeholder-on-gray": "var(--text-placeholder-on-gray)",
        "text-placeholder-on-gray-on-white": "var(--text-placeholder-on-gray-on-white)",
        "tipsy-button-text-purple": "var(--tipsy-button-text-purple)",
        "tipsy-chat-box-gray": "var(--tipsy-chat-box-gray)",
        "tipsy-chat-box-magenta": "var(--tipsy-chat-box-magenta)",
        "tipsy-faded-mauve": "var(--tipsy-faded-mauve)",
        "tipsy-grey-dark-button": "var(--tipsy-grey-dark-button)",
        "tipsy-grey-light-button": "var(--tipsy-grey-light-button)",
        "tipsy-lavendar-rose": "var(--tipsy-lavendar-rose)",
        "tipsy-light-orchid": "var(--tipsy-light-orchid)",
        "tipsy-lilac-bush": "var(--tipsy-lilac-bush)",
        "tipsy-purple-action": "var(--tipsy-purple-action)",
        "tipsy-purple-text": "var(--tipsy-purple-text)",
        "tipsy-white-text": "var(--tipsy-white-text)",
        "tokens-bronze-medal": "var(--tokens-bronze-medal)",
        "tokens-color-button-background-primary": "var(--tokens-color-button-background-primary)",
        "tokens-color-button-label-primary": "var(--tokens-color-button-label-primary)",
        "tokens-color-surface-primary": "var(--tokens-color-surface-primary)",
        "tokens-color-text-action-secondary": "var(--tokens-color-text-action-secondary)",
        "tokens-color-text-white-primary": "var(--tokens-color-text-white-primary)",
        "tokens-gold-medal": "var(--tokens-gold-medal)",
        "tokens-purple-tag": "var(--tokens-purple-tag)",
        "tokens-silver-medal": "var(--tokens-silver-medal)",
        "vm-dark-gray": "var(--vm-dark-gray)",
        "vm-white": "var(--vm-white)",
        "website-accents": "var(--website-accents)",
        yellow: "var(--yellow)",
        "yellow-text-on-white": "var(--yellow-text-on-white)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "buttons-and-2nd-headers": "var(--buttons-and-2nd-headers-font-family)",
        CTA: "var(--CTA-font-family)",
        "customer-questions": "var(--customer-questions-font-family)",
        "kaushan-script": "var(--kaushan-script-font-family)",
        "kaushan-script0-BOLD-GET-TIPSY-FONT": "var(--kaushan-script0-BOLD-GET-TIPSY-FONT-font-family)",
        logo: "var(--logo-font-family)",
        "main-app-font": "var(--main-app-font-font-family)",
        "paragraph-text": "var(--paragraph-text-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
        raleway: ['Raleway', 'sans-serif'],
      },
      boxShadow: {
        cards: "var(--cards)",
        "main-buttons": "var(--main-buttons)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  darkMode: ["class"],
};
